# sed -r -e 's/([a-z]+) \(([0-9]+)\)( -> ([a-z ,]+))?/wg["\1"]=\2\ndep["\1"]=["\4"]/' day7.in > day7.py

wg = {}
dep = {}

wg["yvpwz"] = 50
dep["yvpwz"] = []
wg["vfosh"] = 261
dep["vfosh"] = ["aziwd", "tubze", "dhjrv"]
wg["xtvawvt"] = 19
dep["xtvawvt"] = []
wg["nspsk"] = 24
dep["nspsk"] = []
wg["sgtfap"] = 19
dep["sgtfap"] = ["bohjocj", "bqvzg"]
wg["oyuteie"] = 52
dep["oyuteie"] = []
wg["irrpz"] = 226
dep["irrpz"] = ["cibfe", "hemjsj", "upbldz"]
wg["vtvku"] = 426
dep["vtvku"] = []
wg["vbsfwqh"] = 6055
dep["vbsfwqh"] = ["govhrck", "pglpu", "rwuflbi", "ppgaoz"]
wg["nupmnv"] = 47
dep["nupmnv"] = ["cngdg", "olgsb", "lmvmb"]
wg["ulndqey"] = 71
dep["ulndqey"] = []
wg["fujgzbt"] = 198
dep["fujgzbt"] = ["fbesgp", "hewtnrw"]
wg["nsbvvsi"] = 39
dep["nsbvvsi"] = []
wg["ajvtdl"] = 36
dep["ajvtdl"] = []
wg["xrgca"] = 85
dep["xrgca"] = []
wg["mksrqb"] = 45
dep["mksrqb"] = []
wg["ozfsktz"] = 56
dep["ozfsktz"] = ["xzwjii", "uhxjy"]
wg["peretma"] = 15
dep["peretma"] = ["suzsw", "ycvvjgc", "cdyhvr", "jixggay"]
wg["boplau"] = 77
dep["boplau"] = ["boggvxt", "cnyasj"]
wg["rzqffr"] = 84
dep["rzqffr"] = ["tbppaj", "htyeqf", "pgnyu", "ruhqn"]
wg["shkkwp"] = 5
dep["shkkwp"] = []
wg["bpptuqh"] = 68
dep["bpptuqh"] = ["ugxls", "zlshut", "ltqljtw"]
wg["bngres"] = 944
dep["bngres"] = ["ktwby", "tblhhg", "jzgpty", "skbprng"]
wg["tjnyo"] = 55
dep["tjnyo"] = []
wg["ujfeg"] = 13
dep["ujfeg"] = ["vldxkw", "kfbsjv", "rlqwaz", "dvwsrc", "ymxlwf", "zvmhx", "wfdxfxq"]
wg["mxplky"] = 35
dep["mxplky"] = []
wg["ezkqh"] = 91
dep["ezkqh"] = []
wg["kozgi"] = 48
dep["kozgi"] = []
wg["pgnyu"] = 94
dep["pgnyu"] = []
wg["yhunajf"] = 25
dep["yhunajf"] = []
wg["pvpmt"] = 77
dep["pvpmt"] = []
wg["cvitrpt"] = 88
dep["cvitrpt"] = []
wg["zjwih"] = 46
dep["zjwih"] = ["cvitrpt", "chtamif"]
wg["mhfnxk"] = 6
dep["mhfnxk"] = ["jddyhz", "gvrhj", "ctpdk", "oprvyxy", "luzjys"]
wg["dbrnqc"] = 77
dep["dbrnqc"] = []
wg["iorlbdv"] = 43
dep["iorlbdv"] = []
wg["twwzhwf"] = 118
dep["twwzhwf"] = ["ndgupvi", "aumbaa"]
wg["mvngvtg"] = 67
dep["mvngvtg"] = []
wg["kwkprrw"] = 187
dep["kwkprrw"] = ["uobxcai", "aklrjg"]
wg["wtvffu"] = 120
dep["wtvffu"] = ["vzxvex", "mtsbrje", "slfile"]
wg["vjwivnq"] = 52
dep["vjwivnq"] = []
wg["cbwbdsv"] = 157
dep["cbwbdsv"] = ["przuau", "atjtgjx"]
wg["rwuflbi"] = 8
dep["rwuflbi"] = ["lapoix", "dkdovw", "spgcwtn"]
wg["upbldz"] = 27
dep["upbldz"] = []
wg["xgnqi"] = 64
dep["xgnqi"] = []
wg["ksotbs"] = 48
dep["ksotbs"] = ["cqbvru", "tqbvdu"]
wg["romrjs"] = 55
dep["romrjs"] = ["vhilqk", "gzxuw"]
wg["ftmwqqj"] = 76
dep["ftmwqqj"] = []
wg["kqpvqie"] = 63
dep["kqpvqie"] = ["qomhp", "fwvsi"]
wg["xxrsnzv"] = 39
dep["xxrsnzv"] = []
wg["trqfblp"] = 85
dep["trqfblp"] = []
wg["rmjktk"] = 28
dep["rmjktk"] = ["wtkfiw", "mlrdsj", "pnicdos", "woujz", "psrzr"]
wg["lwygknn"] = 96
dep["lwygknn"] = []
wg["ctgbkrb"] = 76
dep["ctgbkrb"] = ["iavuhwe", "onvkja"]
wg["iqbrs"] = 67
dep["iqbrs"] = ["tghoyv", "hoheog", "kjpzwp", "wwvad", "ezmjqnt"]
wg["efuqu"] = 136
dep["efuqu"] = ["umljkr", "qblnh"]
wg["egwjjg"] = 85
dep["egwjjg"] = []
wg["dgtvwiy"] = 27
dep["dgtvwiy"] = []
wg["ndgupvi"] = 28
dep["ndgupvi"] = []
wg["zdvai"] = 85
dep["zdvai"] = []
wg["auhio"] = 82
dep["auhio"] = []
wg["dywjt"] = 40
dep["dywjt"] = []
wg["hhboca"] = 18
dep["hhboca"] = []
wg["pptbkz"] = 96
dep["pptbkz"] = []
wg["iqsvbk"] = 73
dep["iqsvbk"] = []
wg["nwjibjk"] = 31
dep["nwjibjk"] = []
wg["veclzy"] = 308
dep["veclzy"] = ["dohjma", "hbiwkt"]
wg["repak"] = 139
dep["repak"] = ["bcjxhps", "eyckbl"]
wg["xguqlvl"] = 74
dep["xguqlvl"] = []
wg["rkjmp"] = 59
dep["rkjmp"] = []
wg["eqviuw"] = 171
dep["eqviuw"] = ["mqlsvih", "lrnjjfq", "njgkkxo"]
wg["zogylog"] = 80
dep["zogylog"] = []
wg["kroqr"] = 38
dep["kroqr"] = []
wg["onvkja"] = 49
dep["onvkja"] = []
wg["tedehrz"] = 94
dep["tedehrz"] = ["ipqjff", "dmiqf"]
wg["lhwyt"] = 287
dep["lhwyt"] = ["jbwbw", "htyyatf", "ppvwkei", "vtbzq", "pynomi", "uswsg"]
wg["mrbqk"] = 64
dep["mrbqk"] = []
wg["aoxtau"] = 64
dep["aoxtau"] = []
wg["gvrhj"] = 59
dep["gvrhj"] = ["qurrva", "xrgca"]
wg["lfksu"] = 72
dep["lfksu"] = []
wg["tnwle"] = 49
dep["tnwle"] = []
wg["dgnpr"] = 93
dep["dgnpr"] = []
wg["ucsxzhl"] = 21
dep["ucsxzhl"] = ["tpefei", "ntkeax", "jvayv", "yuobv"]
wg["wbibf"] = 183
dep["wbibf"] = ["pvtat", "ygnww", "akngdu", "swpkkpi"]
wg["ljaktj"] = 21939
dep["ljaktj"] = ["seeqikh", "mqrfbqc", "ihnus"]
wg["agqkf"] = 69
dep["agqkf"] = []
wg["tubze"] = 48
dep["tubze"] = []
wg["fcapw"] = 105
dep["fcapw"] = ["nkhzrd", "shkkwp"]
wg["sdied"] = 47
dep["sdied"] = []
wg["zfmeblt"] = 56
dep["zfmeblt"] = []
wg["wqyzjzi"] = 41
dep["wqyzjzi"] = []
wg["zxjeza"] = 185
dep["zxjeza"] = ["ioumv", "pjersb"]
wg["vecxd"] = 56
dep["vecxd"] = ["civozek", "qzsypj"]
wg["dkxebg"] = 73
dep["dkxebg"] = ["atrmuc", "mhfnxk", "zwwbw", "ryaotx", "yqhmb", "yztqpc"]
wg["oqiye"] = 35
dep["oqiye"] = []
wg["edyqn"] = 60
dep["edyqn"] = []
wg["fujwzoc"] = 404
dep["fujwzoc"] = []
wg["llcbiqi"] = 79
dep["llcbiqi"] = []
wg["yejkld"] = 41
dep["yejkld"] = []
wg["utbev"] = 25
dep["utbev"] = ["hsxru", "jfuxeo", "zyshq", "eznabc", "lgsda", "uobxonm"]
wg["ojxyv"] = 79
dep["ojxyv"] = []
wg["vbpde"] = 20
dep["vbpde"] = []
wg["fyjowg"] = 26
dep["fyjowg"] = []
wg["yfzjc"] = 31
dep["yfzjc"] = []
wg["obwzec"] = 41
dep["obwzec"] = []
wg["zcanxq"] = 85
dep["zcanxq"] = []
wg["woujz"] = 125
dep["woujz"] = ["qntvn", "kwzrzn"]
wg["adhwzp"] = 305
dep["adhwzp"] = ["agqkf", "yallk"]
wg["zvcfznz"] = 184
dep["zvcfznz"] = ["rjuhrpu", "yzwnh", "hikik"]
wg["dxbrl"] = 66
dep["dxbrl"] = []
wg["appays"] = 423
dep["appays"] = ["nupmnv", "cyppxr", "rqoczb"]
wg["rgndu"] = 81
dep["rgndu"] = ["tsbbzu", "dtxrjg"]
wg["jncex"] = 74
dep["jncex"] = ["rrdczem", "bhhgpe", "gtvnow", "vndrx"]
wg["cfvbuip"] = 53
dep["cfvbuip"] = []
wg["vsqfx"] = 29
dep["vsqfx"] = []
wg["zocaag"] = 38
dep["zocaag"] = []
wg["ppymmsf"] = 19
dep["ppymmsf"] = []
wg["amwxj"] = 69
dep["amwxj"] = ["pptbkz", "kweqtf", "jwmbs"]
wg["svadhfo"] = 99
dep["svadhfo"] = []
wg["xdsbnr"] = 8
dep["xdsbnr"] = []
wg["duvrzrl"] = 22
dep["duvrzrl"] = []
wg["dfaro"] = 8
dep["dfaro"] = []
wg["vgugdtt"] = 220
dep["vgugdtt"] = ["nxpakq", "fhsecp"]
wg["fwddmmv"] = 43
dep["fwddmmv"] = []
wg["igaww"] = 28
dep["igaww"] = []
wg["bbxbrsh"] = 31
dep["bbxbrsh"] = []
wg["swpkkpi"] = 13
dep["swpkkpi"] = []
wg["bkqexxz"] = 77
dep["bkqexxz"] = []
wg["ovfduq"] = 16
dep["ovfduq"] = []
wg["rtzce"] = 39
dep["rtzce"] = []
wg["gmwto"] = 119
dep["gmwto"] = ["wbeizj", "refgrip"]
wg["rmdhj"] = 24
dep["rmdhj"] = []
wg["yeref"] = 77
dep["yeref"] = []
wg["ifstrgw"] = 23
dep["ifstrgw"] = ["qpixldb", "tukirqp", "bwcyqb", "bzbmt"]
wg["untdpje"] = 45
dep["untdpje"] = ["owimy", "yejkld"]
wg["esiwujq"] = 41
dep["esiwujq"] = []
wg["emvxet"] = 131
dep["emvxet"] = ["vecdh", "ftgvx"]
wg["mztuzb"] = 764
dep["mztuzb"] = ["jgzvrf", "eaqiocy", "fsagr"]
wg["bwnabqh"] = 83
dep["bwnabqh"] = []
wg["gypsfc"] = 43
dep["gypsfc"] = []
wg["bhemin"] = 44
dep["bhemin"] = []
wg["imydd"] = 164
dep["imydd"] = ["iabqb", "vdpnsak"]
wg["qajpehv"] = 49
dep["qajpehv"] = []
wg["oxnfnsv"] = 76
dep["oxnfnsv"] = ["twwzhwf", "uiyyc", "gfaamu", "umhcrc", "bcjpzpk", "vrqeade"]
wg["qfdldyu"] = 231
dep["qfdldyu"] = []
wg["dmsmgs"] = 29
dep["dmsmgs"] = []
wg["oqady"] = 7
dep["oqady"] = ["mhtzh", "cpreh"]
wg["zbhwrc"] = 759
dep["zbhwrc"] = ["esrilo", "dcngdo"]
wg["cyppxr"] = 272
dep["cyppxr"] = ["pitmcu", "nvlqab"]
wg["jtzjrke"] = 45
dep["jtzjrke"] = []
wg["przuau"] = 59
dep["przuau"] = []
wg["eexkce"] = 44
dep["eexkce"] = []
wg["xsewlv"] = 124
dep["xsewlv"] = ["fwfpmti", "rszjhxn"]
wg["fbesgp"] = 28
dep["fbesgp"] = []
wg["sxegjbz"] = 297
dep["sxegjbz"] = ["yhycc", "gxmry", "favzt"]
wg["nxpakq"] = 17
dep["nxpakq"] = []
wg["hbvvse"] = 98
dep["hbvvse"] = []
wg["ygzwut"] = 83
dep["ygzwut"] = []
wg["cngdg"] = 93
dep["cngdg"] = []
wg["tfzum"] = 69
dep["tfzum"] = []
wg["ccghjn"] = 58
dep["ccghjn"] = []
wg["ylbpwah"] = 190
dep["ylbpwah"] = ["htlpx", "eduzave", "peqgox", "fkqkfdu"]
wg["mobbhp"] = 141
dep["mobbhp"] = ["clgbo", "jtzjrke"]
wg["icdlpb"] = 62
dep["icdlpb"] = []
wg["wkrtcw"] = 1663
dep["wkrtcw"] = ["qqzhz", "ybewhak", "mazbb"]
wg["uswsg"] = 312
dep["uswsg"] = []
wg["zdvlgn"] = 63
dep["zdvlgn"] = ["rmpryj", "qrtdtt"]
wg["hfcifm"] = 107
dep["hfcifm"] = ["tpfuxx", "wdivd"]
wg["cltqhc"] = 25
dep["cltqhc"] = []
wg["gnrnwtz"] = 513
dep["gnrnwtz"] = ["efxakc", "jxlgwb", "ksotbs", "gvayfu", "wqvtdc"]
wg["rdufpid"] = 25
dep["rdufpid"] = []
wg["kszmj"] = 137
dep["kszmj"] = ["eemfgbx", "amvjukd"]
wg["ykuto"] = 662
dep["ykuto"] = ["pvuoltd", "kcyiwqs", "kbjnzw", "kszmj"]
wg["ckswvj"] = 264
dep["ckswvj"] = ["cleanrs", "ntixh"]
wg["czhsx"] = 51
dep["czhsx"] = []
wg["luayjsp"] = 47
dep["luayjsp"] = ["alhjba", "qjghc"]
wg["djnsvq"] = 295
dep["djnsvq"] = ["nbnqidn", "ijjfn"]
wg["qxzfv"] = 57
dep["qxzfv"] = []
wg["qyzja"] = 94
dep["qyzja"] = []
wg["rmpryj"] = 96
dep["rmpryj"] = []
wg["eyreht"] = 45
dep["eyreht"] = []
wg["vzkii"] = 216
dep["vzkii"] = []
wg["rwheyic"] = 68
dep["rwheyic"] = []
wg["rjmdre"] = 21
dep["rjmdre"] = []
wg["qntvn"] = 71
dep["qntvn"] = []
wg["lescv"] = 32
dep["lescv"] = []
wg["qomhp"] = 32
dep["qomhp"] = []
wg["oegwh"] = 70
dep["oegwh"] = []
wg["tukirqp"] = 85
dep["tukirqp"] = []
wg["pumxr"] = 103
dep["pumxr"] = ["wvpwez", "kiuiq"]
wg["fjrpc"] = 89
dep["fjrpc"] = []
wg["gmoliax"] = 1327
dep["gmoliax"] = ["jniisu", "cfafhwl"]
wg["wsrwgvc"] = 80
dep["wsrwgvc"] = []
wg["zhgzg"] = 62
dep["zhgzg"] = ["aonfu", "vqiqglo"]
wg["fxcuah"] = 208
dep["fxcuah"] = ["uofigyp", "kfxyzqc"]
wg["fnjnhmk"] = 76
dep["fnjnhmk"] = []
wg["zlshut"] = 62
dep["zlshut"] = []
wg["hsnbry"] = 26
dep["hsnbry"] = []
wg["pjnyxo"] = 30
dep["pjnyxo"] = []
wg["luzjys"] = 115
dep["luzjys"] = ["kisjb", "owsosl"]
wg["vecdh"] = 14
dep["vecdh"] = []
wg["vfrqc"] = 13
dep["vfrqc"] = []
wg["udjcwm"] = 18
dep["udjcwm"] = []
wg["twpmx"] = 30
dep["twpmx"] = []
wg["oiysq"] = 64
dep["oiysq"] = []
wg["lcazsyd"] = 78
dep["lcazsyd"] = []
wg["ryaotx"] = 399
dep["ryaotx"] = ["lmctbp", "imydd", "wlkatbq", "sikzsc"]
wg["rbnfwkf"] = 51
dep["rbnfwkf"] = []
wg["kdtpg"] = 4260
dep["kdtpg"] = ["lymwlyg", "xgqzb", "appays"]
wg["djvps"] = 30
dep["djvps"] = []
wg["vjqjwk"] = 76
dep["vjqjwk"] = []
wg["pbrdt"] = 66
dep["pbrdt"] = []
wg["rciilr"] = 33
dep["rciilr"] = []
wg["heumdl"] = 75
dep["heumdl"] = []
wg["whqvs"] = 146
dep["whqvs"] = ["ttxrd", "qxuakjr"]
wg["zvtxa"] = 77
dep["zvtxa"] = []
wg["cpkkq"] = 18
dep["cpkkq"] = ["romrjs", "xmpdevf", "nnofr", "qgqou", "nmkjx", "nbvwta"]
wg["sxada"] = 7
dep["sxada"] = ["dgrwv", "irlfj", "rmjpia", "ciafn"]
wg["frbmr"] = 67
dep["frbmr"] = ["tnwle", "nnyqes"]
wg["tgksxw"] = 53
dep["tgksxw"] = ["dkffgot", "yvpwz"]
wg["ijvux"] = 77
dep["ijvux"] = []
wg["tblhhg"] = 44
dep["tblhhg"] = []
wg["xxsivgz"] = 17
dep["xxsivgz"] = ["kkhfzgn", "rbqcbvl"]
wg["ylxxmlt"] = 83
dep["ylxxmlt"] = ["qxzfv", "dacbtyf", "aqhcy"]
wg["vndrx"] = 248
dep["vndrx"] = ["xecqd", "tznkdt"]
wg["jwezuh"] = 57
dep["jwezuh"] = ["kxrxtq", "cijfsu"]
wg["ztqvzwj"] = 86
dep["ztqvzwj"] = []
wg["dluyef"] = 1987
dep["dluyef"] = ["zcicmp", "qkhhg", "eivrwbt", "iqzdu", "rmvry"]
wg["ybzvav"] = 873
dep["ybzvav"] = ["agwyte", "kawloxz", "bmdxyf"]
wg["pvuoltd"] = 115
dep["pvuoltd"] = ["glgrdm", "gfizf", "bnehbkl", "lkyeyn"]
wg["ceefghr"] = 21
dep["ceefghr"] = ["mksrqb", "saqjax", "llild", "qwvvha"]
wg["khphs"] = 101
dep["khphs"] = ["qwlepd", "acgrw"]
wg["yxvgj"] = 13
dep["yxvgj"] = []
wg["zifogt"] = 85
dep["zifogt"] = []
wg["wgwlbz"] = 83
dep["wgwlbz"] = ["uwaij", "qklota"]
wg["xlyvge"] = 235
dep["xlyvge"] = ["zgnoqml", "trqfblp"]
wg["qaxvec"] = 41
dep["qaxvec"] = []
wg["ylkfgx"] = 6
dep["ylkfgx"] = []
wg["pzgvdt"] = 37
dep["pzgvdt"] = []
wg["vtzdfjg"] = 77
dep["vtzdfjg"] = []
wg["tyiekxm"] = 24
dep["tyiekxm"] = []
wg["jaiqusy"] = 18
dep["jaiqusy"] = []
wg["avhkram"] = 73
dep["avhkram"] = []
wg["akluijb"] = 77
dep["akluijb"] = []
wg["bohjocj"] = 73
dep["bohjocj"] = []
wg["ofoto"] = 1287
dep["ofoto"] = ["sgrcmj", "jxykl"]
wg["qgqou"] = 227
dep["qgqou"] = []
wg["xtoaq"] = 18
dep["xtoaq"] = []
wg["peqgox"] = 25
dep["peqgox"] = []
wg["kobcmy"] = 64
dep["kobcmy"] = ["haeymgy", "egwjjg", "zcanxq", "zifogt"]
wg["namzy"] = 79
dep["namzy"] = []
wg["vldxkw"] = 463
dep["vldxkw"] = ["gmwto", "aflmt", "boplau", "khphs", "qlthpj", "epqsj"]
wg["chtamif"] = 88
dep["chtamif"] = []
wg["vqsuh"] = 92
dep["vqsuh"] = []
wg["iofsrh"] = 35
dep["iofsrh"] = []
wg["njgkkxo"] = 17
dep["njgkkxo"] = []
wg["zsqqhe"] = 94
dep["zsqqhe"] = []
wg["xupdam"] = 64
dep["xupdam"] = []
wg["bqvzg"] = 73
dep["bqvzg"] = []
wg["hmetm"] = 889
dep["hmetm"] = ["aklagd", "ceefghr", "whcxfwf", "guztl"]
wg["hoheog"] = 296
dep["hoheog"] = []
wg["llsvd"] = 18
dep["llsvd"] = []
wg["giupn"] = 30
dep["giupn"] = []
wg["dfzfwun"] = 64
dep["dfzfwun"] = []
wg["nmfvmam"] = 125
dep["nmfvmam"] = ["qxwlhxh", "obwzec"]
wg["ioumv"] = 86
dep["ioumv"] = []
wg["gxmry"] = 143
dep["gxmry"] = ["cyvplfd", "wmcusr"]
wg["ywgvsdb"] = 131
dep["ywgvsdb"] = ["fzfxs", "yvdkbo", "igaww"]
wg["pwsye"] = 49
dep["pwsye"] = []
wg["mywezi"] = 407
dep["mywezi"] = ["gimkyms", "bnxvusb"]
wg["fzfxs"] = 28
dep["fzfxs"] = []
wg["kurgrkq"] = 76
dep["kurgrkq"] = []
wg["txeucf"] = 61
dep["txeucf"] = []
wg["gjwflt"] = 84
dep["gjwflt"] = ["xmfzu", "gcbjhu", "xxnannn", "bwnabqh"]
wg["vrgxe"] = 1226
dep["vrgxe"] = ["zbfyg", "rocbcw", "zouml", "wbibf"]
wg["izwze"] = 16
dep["izwze"] = []
wg["jwmbs"] = 96
dep["jwmbs"] = []
wg["euvev"] = 46
dep["euvev"] = []
wg["dgzvf"] = 30
dep["dgzvf"] = []
wg["iezdimc"] = 82
dep["iezdimc"] = []
wg["zkhll"] = 992
dep["zkhll"] = ["bbqtwv", "xupdam"]
wg["jhxxfq"] = 71
dep["jhxxfq"] = []
wg["hemjsj"] = 27
dep["hemjsj"] = []
wg["ryxkvxj"] = 124
dep["ryxkvxj"] = ["bhemin", "apghde"]
wg["qxuakjr"] = 54
dep["qxuakjr"] = []
wg["aonfu"] = 95
dep["aonfu"] = []
wg["dvopaww"] = 98
dep["dvopaww"] = []
wg["uobwwa"] = 69
dep["uobwwa"] = []
wg["dojvyuv"] = 96
dep["dojvyuv"] = []
wg["ezcmm"] = 886
dep["ezcmm"] = ["ntjmwf", "qfdldyu", "vokxlx"]
wg["yzwnh"] = 15
dep["yzwnh"] = []
wg["jfqanu"] = 302
dep["jfqanu"] = ["dcgarog", "tcpqh"]
wg["gfizf"] = 14
dep["gfizf"] = []
wg["kvbdsv"] = 46
dep["kvbdsv"] = []
wg["qzsypj"] = 98
dep["qzsypj"] = []
wg["vyffcrm"] = 24
dep["vyffcrm"] = []
wg["iuoxs"] = 13
dep["iuoxs"] = []
wg["zitfb"] = 23
dep["zitfb"] = ["ctagl", "ddpgq"]
wg["yueoma"] = 46
dep["yueoma"] = []
wg["bbqtwv"] = 64
dep["bbqtwv"] = []
wg["hgsng"] = 45
dep["hgsng"] = []
wg["wgehfu"] = 77
dep["wgehfu"] = ["lescv", "hnjbsg", "bxvwe", "evmuxia"]
wg["arwqmho"] = 66
dep["arwqmho"] = []
wg["amvjukd"] = 17
dep["amvjukd"] = []
wg["ntixh"] = 10
dep["ntixh"] = []
wg["zfzblty"] = 47
dep["zfzblty"] = []
wg["cxzuprb"] = 592
dep["cxzuprb"] = ["texfyi", "dvgstr", "irhxzg"]
wg["ekqux"] = 76
dep["ekqux"] = []
wg["abxalr"] = 697
dep["abxalr"] = ["zjwih", "gjwuf", "eqviuw"]
wg["choiui"] = 65
dep["choiui"] = []
wg["tgjdwlh"] = 24
dep["tgjdwlh"] = []
wg["glhsr"] = 60
dep["glhsr"] = []
wg["rtymngs"] = 66
dep["rtymngs"] = []
wg["rocbcw"] = 169
dep["rocbcw"] = ["djizg", "dtnaqds"]
wg["bjwws"] = 46
dep["bjwws"] = ["evgtp", "ztqvzwj"]
wg["gowbiey"] = 78
dep["gowbiey"] = []
wg["yqhmb"] = 497
dep["yqhmb"] = ["njgrpbo", "tedehrz", "bjwws"]
wg["lapoix"] = 240
dep["lapoix"] = ["xkizl", "dyhate", "disan"]
wg["vckqsrm"] = 30
dep["vckqsrm"] = []
wg["sxdljm"] = 66
dep["sxdljm"] = []
wg["frpmd"] = 13
dep["frpmd"] = []
wg["uwhwsv"] = 86
dep["uwhwsv"] = []
wg["wknic"] = 47
dep["wknic"] = []
wg["pnicdos"] = 165
dep["pnicdos"] = ["czhsx", "rbnfwkf"]
wg["wrsik"] = 80
dep["wrsik"] = []
wg["wbogdd"] = 66
dep["wbogdd"] = ["eibtll", "ppmvpn"]
wg["fyrqw"] = 28
dep["fyrqw"] = ["ekqux", "zxoqwjv", "ipogzy", "dhzuvup"]
wg["uttjzap"] = 22
dep["uttjzap"] = []
wg["gqjkk"] = 41
dep["gqjkk"] = []
wg["gcbjhu"] = 83
dep["gcbjhu"] = []
wg["bnxvusb"] = 21
dep["bnxvusb"] = []
wg["bxvwe"] = 32
dep["bxvwe"] = []
wg["difjqqd"] = 47
dep["difjqqd"] = []
wg["xxnannn"] = 83
dep["xxnannn"] = []
wg["lxzucvk"] = 94
dep["lxzucvk"] = []
wg["ehynj"] = 98
dep["ehynj"] = ["ijvuozb", "wutdi"]
wg["vwkbje"] = 25
dep["vwkbje"] = []
wg["ciafn"] = 62
dep["ciafn"] = []
wg["pyyuj"] = 34
dep["pyyuj"] = []
wg["zofljd"] = 685
dep["zofljd"] = ["hfcifm", "emvxet", "ahrdgu"]
wg["zyshq"] = 140
dep["zyshq"] = ["dpcmm", "eosuf"]
wg["zgslahq"] = 101
dep["zgslahq"] = ["ximrxj", "auvxopo"]
wg["xszci"] = 72
dep["xszci"] = []
wg["fomxzjj"] = 47
dep["fomxzjj"] = []
wg["mcduoz"] = 6
dep["mcduoz"] = []
wg["rcltx"] = 73
dep["rcltx"] = ["djnsvq", "hqmum", "ifstrgw"]
wg["pemna"] = 98
dep["pemna"] = []
wg["fgnsyw"] = 39
dep["fgnsyw"] = []
wg["tfppg"] = 77
dep["tfppg"] = ["uwhwsv", "fmapm"]
wg["tohlady"] = 84
dep["tohlady"] = []
wg["gzxuw"] = 86
dep["gzxuw"] = []
wg["mkdiuil"] = 96
dep["mkdiuil"] = []
wg["qfhkgt"] = 52
dep["qfhkgt"] = []
wg["csxwyly"] = 47
dep["csxwyly"] = []
wg["intuzzk"] = 82
dep["intuzzk"] = ["jqqxv", "dlnyi", "pbides", "qtcqtv"]
wg["bfxhl"] = 78
dep["bfxhl"] = ["qvmorke", "pazbvum"]
wg["eduzave"] = 25
dep["eduzave"] = []
wg["kwbni"] = 74
dep["kwbni"] = ["abxalr", "bbsuv", "gnrnwtz", "rmjktk", "eqcnl", "pdwesa", "sunvhgy"]
wg["hhnvuv"] = 83
dep["hhnvuv"] = []
wg["ismgnve"] = 68
dep["ismgnve"] = []
wg["alhjba"] = 84
dep["alhjba"] = []
wg["mspkmg"] = 94
dep["mspkmg"] = []
wg["rszjhxn"] = 34
dep["rszjhxn"] = []
wg["frleu"] = 60
dep["frleu"] = []
wg["mewfm"] = 48
dep["mewfm"] = ["gowbiey", "yevks"]
wg["mpulnxr"] = 42
dep["mpulnxr"] = ["eziuhsd", "xsewlv", "tckcxhb", "bfxhl"]
wg["mzksj"] = 68
dep["mzksj"] = []
wg["shnqfh"] = 1649
dep["shnqfh"] = ["wnnov", "mdtniv", "fwpuy"]
wg["bxpfop"] = 153
dep["bxpfop"] = []
wg["zucsr"] = 26
dep["zucsr"] = []
wg["gmpqmio"] = 93
dep["gmpqmio"] = []
wg["wzjbp"] = 174
dep["wzjbp"] = []
wg["zcicmp"] = 301
dep["zcicmp"] = []
wg["ppvwkei"] = 93
dep["ppvwkei"] = ["eqjfyj", "lghygm", "grrycy"]
wg["tcsoaw"] = 239
dep["tcsoaw"] = ["kzfzp", "oypzs"]
wg["nnsial"] = 78
dep["nnsial"] = []
wg["mazbb"] = 98
dep["mazbb"] = ["dsxhhub", "fqoqkzk"]
wg["lclbeiq"] = 81
dep["lclbeiq"] = ["bwxicc", "uttjzap"]
wg["jddyhz"] = 91
dep["jddyhz"] = ["vmmww", "mvalh"]
wg["umqrwk"] = 132
dep["umqrwk"] = ["itvhd", "jbuxnpr", "mxopf"]
wg["qxfan"] = 34
dep["qxfan"] = []
wg["cdafdq"] = 26
dep["cdafdq"] = []
wg["drrjnr"] = 80
dep["drrjnr"] = []
wg["kxrxtq"] = 68
dep["kxrxtq"] = []
wg["cnyasj"] = 56
dep["cnyasj"] = []
wg["kpdbki"] = 38
dep["kpdbki"] = []
wg["dgzoyx"] = 72
dep["dgzoyx"] = []
wg["zwwbw"] = 155
dep["zwwbw"] = ["eqbvn", "qcghv", "tfppg", "xaanoft"]
wg["zsxbg"] = 22
dep["zsxbg"] = []
wg["fwvsi"] = 32
dep["fwvsi"] = []
wg["hefgter"] = 6
dep["hefgter"] = ["pirieql", "hikocbe"]
wg["mwelezd"] = 81
dep["mwelezd"] = []
wg["eptcqns"] = 16
dep["eptcqns"] = []
wg["jmbiky"] = 96
dep["jmbiky"] = []
wg["gnozwfo"] = 242
dep["gnozwfo"] = ["vqsuh", "cxlfgl"]
wg["wtkfiw"] = 48
dep["wtkfiw"] = ["owresw", "grqjew", "okbzzwd"]
wg["ltqljtw"] = 62
dep["ltqljtw"] = []
wg["lymwlyg"] = 72
dep["lymwlyg"] = ["snkox", "adhwzp", "cvdjts"]
wg["mgeizij"] = 60
dep["mgeizij"] = ["sbcuc", "rqrfl"]
wg["zghvta"] = 57
dep["zghvta"] = []
wg["uqcqc"] = 85
dep["uqcqc"] = []
wg["tozwp"] = 19
dep["tozwp"] = []
wg["nqjrds"] = 81
dep["nqjrds"] = []
wg["cfufhn"] = 11
dep["cfufhn"] = []
wg["yznhjg"] = 60
dep["yznhjg"] = ["choiui", "yhecio", "lprpgxe"]
wg["qtbhnxr"] = 27
dep["qtbhnxr"] = []
wg["bwdfws"] = 27
dep["bwdfws"] = []
wg["kiuiq"] = 89
dep["kiuiq"] = []
wg["zjfrc"] = 141
dep["zjfrc"] = ["zghvta", "lkqiqa"]
wg["ooiyeep"] = 80
dep["ooiyeep"] = []
wg["xiawjb"] = 38
dep["xiawjb"] = []
wg["wgzdt"] = 216
dep["wgzdt"] = ["vfrqc", "frpmd"]
wg["lugkrb"] = 36
dep["lugkrb"] = []
wg["mvalh"] = 69
dep["mvalh"] = []
wg["cruxrmy"] = 52
dep["cruxrmy"] = []
wg["azwmkej"] = 33
dep["azwmkej"] = []
wg["tqbvdu"] = 61
dep["tqbvdu"] = []
wg["szvlte"] = 21
dep["szvlte"] = []
wg["bzbmt"] = 85
dep["bzbmt"] = []
wg["gcczhgd"] = 43
dep["gcczhgd"] = ["eecoekq", "kwpnxyh"]
wg["jxlgwb"] = 24
dep["jxlgwb"] = ["pzahn", "yadtxl"]
wg["gfaamu"] = 8
dep["gfaamu"] = ["ygzwut", "hhnvuv"]
wg["ntjmwf"] = 211
dep["ntjmwf"] = ["owqdo", "umvvwsq"]
wg["rqhrb"] = 19
dep["rqhrb"] = []
wg["jixggay"] = 28
dep["jixggay"] = []
wg["gavjzk"] = 91
dep["gavjzk"] = []
wg["mbydswv"] = 69
dep["mbydswv"] = []
wg["unqbwiz"] = 10
dep["unqbwiz"] = ["rixge", "lkwapf", "phvbwg"]
wg["veycd"] = 62
dep["veycd"] = []
wg["lmctbp"] = 106
dep["lmctbp"] = ["wqyzjzi", "gqjkk"]
wg["jwpjy"] = 94
dep["jwpjy"] = ["ywlub", "rtymngs"]
wg["febjzqn"] = 46461
dep["febjzqn"] = ["mwtojre", "iqmqju", "dkxebg"]
wg["yvdkbo"] = 28
dep["yvdkbo"] = []
wg["iayzdx"] = 7181
dep["iayzdx"] = ["fakyd", "fjwmd", "uzicvdh"]
wg["uobxonm"] = 118
dep["uobxonm"] = ["wrsik", "wsrwgvc"]
wg["sehxgj"] = 41
dep["sehxgj"] = ["wpezjoi", "dcnuouj", "vrpqev", "kjwvqdz", "vzkii"]
wg["eziuhsd"] = 192
dep["eziuhsd"] = []
wg["gcichoe"] = 79
dep["gcichoe"] = []
wg["jwzmsv"] = 45
dep["jwzmsv"] = []
wg["fmapm"] = 86
dep["fmapm"] = []
wg["rbtvx"] = 53
dep["rbtvx"] = []
wg["sgkksme"] = 94
dep["sgkksme"] = []
wg["zmces"] = 86
dep["zmces"] = []
wg["rmjpia"] = 62
dep["rmjpia"] = []
wg["feiki"] = 376
dep["feiki"] = ["oqady", "fcymcb", "wlleabp"]
wg["sgrcmj"] = 54
dep["sgrcmj"] = []
wg["dohjma"] = 76
dep["dohjma"] = []
wg["kgzqclo"] = 71
dep["kgzqclo"] = []
wg["eqjfyj"] = 73
dep["eqjfyj"] = []
wg["zcjrk"] = 1009
dep["zcjrk"] = ["zdvlgn", "sxada", "yznhjg", "pnoxhe"]
wg["zhudrmb"] = 78
dep["zhudrmb"] = ["mvngvtg", "kvags"]
wg["iylwxgn"] = 98
dep["iylwxgn"] = ["edebwk", "gjwflt", "rlapq"]
wg["beraoor"] = 10
dep["beraoor"] = ["pumxr", "gasnep", "ulznkvm"]
wg["gxnoomf"] = 185
dep["gxnoomf"] = ["ihrhkj", "cfufhn"]
wg["fhoprd"] = 71
dep["fhoprd"] = []
wg["pbides"] = 59
dep["pbides"] = []
wg["xqgjvz"] = 192
dep["xqgjvz"] = ["twpmx", "zwofu"]
wg["mexuge"] = 52
dep["mexuge"] = []
wg["rbfbf"] = 47
dep["rbfbf"] = []
wg["oprvyxy"] = 125
dep["oprvyxy"] = ["oyuteie", "yibxqhs"]
wg["eqcnl"] = 637
dep["eqcnl"] = ["kgjcj", "wgzdt", "rrgffal"]
wg["kikfs"] = 40
dep["kikfs"] = []
wg["ntvul"] = 77
dep["ntvul"] = []
wg["bwxicc"] = 22
dep["bwxicc"] = []
wg["rttwea"] = 55
dep["rttwea"] = ["fnjnhmk", "kurgrkq"]
wg["kfxyzqc"] = 9
dep["kfxyzqc"] = []
wg["ddmrgzp"] = 69
dep["ddmrgzp"] = []
wg["clgbo"] = 45
dep["clgbo"] = []
wg["qoapjhr"] = 173
dep["qoapjhr"] = []
wg["kkhfzgn"] = 88
dep["kkhfzgn"] = []
wg["njgrpbo"] = 74
dep["njgrpbo"] = ["dgzoyx", "rlywif"]
wg["bwcyqb"] = 85
dep["bwcyqb"] = []
wg["esrilo"] = 47
dep["esrilo"] = []
wg["blutjw"] = 717
dep["blutjw"] = ["fxcuah", "efuqu", "jwpjy"]
wg["owimy"] = 41
dep["owimy"] = []
wg["oeeqrsd"] = 62
dep["oeeqrsd"] = []
wg["akoqk"] = 16
dep["akoqk"] = []
wg["owqdo"] = 10
dep["owqdo"] = []
wg["fwpuy"] = 26
dep["fwpuy"] = ["eqnpvwk", "lbhxdbr", "lqqkjjr", "tlvpv"]
wg["tzqzk"] = 52
dep["tzqzk"] = []
wg["gxobd"] = 91
dep["gxobd"] = []
wg["npqroe"] = 36
dep["npqroe"] = []
wg["pstaxvr"] = 761
dep["pstaxvr"] = ["peretma", "kqpvqie", "untdpje"]
wg["boggvxt"] = 56
dep["boggvxt"] = []
wg["uobxcai"] = 10
dep["uobxcai"] = []
wg["vmyda"] = 63912
dep["vmyda"] = ["rcltx", "ajwxaa", "yvqasth"]
wg["jznrci"] = 51
dep["jznrci"] = ["mclgebd", "emdsyso"]
wg["ktgfsm"] = 50
dep["ktgfsm"] = []
wg["kweqtf"] = 96
dep["kweqtf"] = []
wg["mtsbrje"] = 66
dep["mtsbrje"] = []
wg["rjuhrpu"] = 15
dep["rjuhrpu"] = []
wg["zgnoqml"] = 85
dep["zgnoqml"] = []
wg["qlthpj"] = 57
dep["qlthpj"] = ["arwqmho", "yydyjr"]
wg["cdudjbj"] = 128
dep["cdudjbj"] = ["iofsrh", "nuuwbui", "mxplky"]
wg["estwket"] = 94
dep["estwket"] = []
wg["adjlg"] = 67
dep["adjlg"] = []
wg["jbwbw"] = 114
dep["jbwbw"] = ["dxbrl", "lhdhko", "fdjhpq"]
wg["ezfky"] = 71
dep["ezfky"] = []
wg["rrdczem"] = 71
dep["rrdczem"] = ["dgrfhvi", "adjlg", "ajyqxh"]
wg["xqrmgdk"] = 6543
dep["xqrmgdk"] = ["unqbwiz", "cxzuprb", "rmkhel"]
wg["nmkjx"] = 213
dep["nmkjx"] = ["wycesn", "gpfipvk"]
wg["qklota"] = 16
dep["qklota"] = []
wg["jbuxnpr"] = 30
dep["jbuxnpr"] = []
wg["xtzqooh"] = 27
dep["xtzqooh"] = []
wg["vbcfe"] = 49938
dep["vbcfe"] = ["yuepckc", "ybzvav", "sxapjc", "cfvlt", "dluyef"]
wg["drzrtpi"] = 96
dep["drzrtpi"] = ["nuuqqqy", "scqutwb"]
wg["xkfps"] = 7
dep["xkfps"] = []
wg["nvxlr"] = 49
dep["nvxlr"] = []
wg["hazbs"] = 31
dep["hazbs"] = []
wg["ajyqxh"] = 67
dep["ajyqxh"] = []
wg["guhyk"] = 66
dep["guhyk"] = []
wg["ipwxws"] = 190
dep["ipwxws"] = ["difjqqd", "wknic"]
wg["akngdu"] = 13
dep["akngdu"] = []
wg["evgtp"] = 86
dep["evgtp"] = []
wg["eznabc"] = 150
dep["eznabc"] = ["dvhbwl", "xnuoisk"]
wg["limjm"] = 52
dep["limjm"] = []
wg["bykjeka"] = 71
dep["bykjeka"] = ["sdied", "zfzblty", "csxwyly", "fomxzjj"]
wg["gpfipvk"] = 7
dep["gpfipvk"] = []
wg["cpreh"] = 86
dep["cpreh"] = []
wg["qurrva"] = 85
dep["qurrva"] = []
wg["sikzsc"] = 46
dep["sikzsc"] = ["dpetvw", "pridma"]
wg["vokxlx"] = 69
dep["vokxlx"] = ["gadnfmt", "nqjrds"]
wg["scbycx"] = 193
dep["scbycx"] = []
wg["qjghc"] = 84
dep["qjghc"] = []
wg["ctpjjsh"] = 964
dep["ctpjjsh"] = ["thlbs", "wgehfu", "fetns"]
wg["uzicvdh"] = 42
dep["uzicvdh"] = ["altsh", "xhhhix", "calvq", "bykjeka", "iucuw"]
wg["tpefei"] = 109
dep["tpefei"] = ["qtznzyx", "myznok"]
wg["sizfqfs"] = 116
dep["sizfqfs"] = ["vsqfx", "dmsmgs"]
wg["qumahjn"] = 71
dep["qumahjn"] = []
wg["ctagl"] = 97
dep["ctagl"] = []
wg["hewtnrw"] = 28
dep["hewtnrw"] = []
wg["ocpzltp"] = 67
dep["ocpzltp"] = []
wg["ihnus"] = 40
dep["ihnus"] = ["vrgxe", "shnqfh", "auzded", "hkhsc", "jwddn", "mcxki", "lhwyt"]
wg["iuydxn"] = 253
dep["iuydxn"] = ["fhoaub", "kmnjo"]
wg["evubadn"] = 49
dep["evubadn"] = []
wg["wpezjoi"] = 112
dep["wpezjoi"] = ["zpxqtrg", "tzqzk"]
wg["qtznzyx"] = 57
dep["qtznzyx"] = []
wg["dcnuouj"] = 76
dep["dcnuouj"] = ["oegwh", "ztzfled"]
wg["ddpgq"] = 97
dep["ddpgq"] = []
wg["ktrkhe"] = 67
dep["ktrkhe"] = []
wg["podcsx"] = 71
dep["podcsx"] = []
wg["univhdj"] = 26
dep["univhdj"] = []
wg["puxaz"] = 60
dep["puxaz"] = []
wg["jadome"] = 50
dep["jadome"] = []
wg["uplbokf"] = 5475
dep["uplbokf"] = ["vbxqhoy", "cpkkq", "iqozz"]
wg["llild"] = 45
dep["llild"] = []
wg["lylaoh"] = 170
dep["lylaoh"] = ["lomhz", "tzjzmmv", "cefbp"]
wg["owsosl"] = 57
dep["owsosl"] = []
wg["iqozz"] = 681
dep["iqozz"] = ["syykbn", "mbmzme", "cdudjbj"]
wg["nvdon"] = 345
dep["nvdon"] = ["dgzvf", "djvps"]
wg["iigqfh"] = 327
dep["iigqfh"] = []
wg["ctatrbo"] = 279
dep["ctatrbo"] = ["tyiekxm", "rmdhj"]
wg["yevks"] = 78
dep["yevks"] = []
wg["cipxwb"] = 85
dep["cipxwb"] = []
wg["edmljb"] = 134
dep["edmljb"] = ["ligev", "glhsr"]
wg["yallk"] = 69
dep["yallk"] = []
wg["owtxsq"] = 71
dep["owtxsq"] = ["zxjeza", "pzgvsxu", "amwxj"]
wg["pejmc"] = 151
dep["pejmc"] = ["fjvoff", "esgqip"]
wg["pridma"] = 71
dep["pridma"] = []
wg["vdpnsak"] = 12
dep["vdpnsak"] = []
wg["hlfbt"] = 200
dep["hlfbt"] = ["univhdj", "xnxdmdb"]
wg["wyuwk"] = 315
dep["wyuwk"] = ["ibcbvy", "ztaff"]
wg["phvbwg"] = 86
dep["phvbwg"] = ["yachdf", "utncpu", "tohlady"]
wg["nbnqidn"] = 34
dep["nbnqidn"] = []
wg["tnyjkok"] = 93
dep["tnyjkok"] = []
wg["kwpnxyh"] = 41
dep["kwpnxyh"] = []
wg["yachdf"] = 84
dep["yachdf"] = []
wg["ximrxj"] = 42
dep["ximrxj"] = []
wg["appok"] = 73
dep["appok"] = []
wg["rrgffal"] = 78
dep["rrgffal"] = ["trxgpy", "zmjfa"]
wg["uiyyc"] = 126
dep["uiyyc"] = ["nspsk", "plxdglq"]
wg["rcxtjte"] = 210
dep["rcxtjte"] = ["drrvse", "szvlte"]
wg["ruild"] = 9
dep["ruild"] = ["zqdezgy", "cxpoqyu"]
wg["mqlsvih"] = 17
dep["mqlsvih"] = []
wg["xgqzb"] = 451
dep["xgqzb"] = ["mgeizij", "hefgter", "ajtjnwp", "ljhezx", "pwwqvhw"]
wg["gmdcbyg"] = 214
dep["gmdcbyg"] = ["mexuge", "limjm"]
wg["mxopf"] = 30
dep["mxopf"] = []
wg["wnnov"] = 170
dep["wnnov"] = []
wg["qgwcfll"] = 95
dep["qgwcfll"] = []
wg["smtbsys"] = 49
dep["smtbsys"] = []
wg["jiyuw"] = 40
dep["jiyuw"] = []
wg["sunvhgy"] = 218
dep["sunvhgy"] = ["fmlhgs", "clmyzsu", "zvcfznz", "xrkca", "jznrci"]
wg["wycesn"] = 7
dep["wycesn"] = []
wg["sbgwln"] = 66
dep["sbgwln"] = []
wg["dkffgot"] = 50
dep["dkffgot"] = []
wg["ximrdyg"] = 217
dep["ximrdyg"] = ["tpbgp", "ibmcytl"]
wg["mvqfvit"] = 38
dep["mvqfvit"] = []
wg["spgcwtn"] = 63
dep["spgcwtn"] = ["yeref", "itxaax", "ntvul"]
wg["apmpzd"] = 46
dep["apmpzd"] = []
wg["njkeu"] = 67
dep["njkeu"] = ["vecxd", "rpcoxd", "emqoxss", "elusirt", "hlfbt", "xqgjvz"]
wg["irlfj"] = 62
dep["irlfj"] = []
wg["zxoqwjv"] = 76
dep["zxoqwjv"] = []
wg["vjwlck"] = 28
dep["vjwlck"] = []
wg["ezmjqnt"] = 146
dep["ezmjqnt"] = ["wdssrl", "gwcig"]
wg["plzfjy"] = 41
dep["plzfjy"] = []
wg["beeeaye"] = 71
dep["beeeaye"] = []
wg["nqkwmyd"] = 254
dep["nqkwmyd"] = []
wg["hbiwkt"] = 76
dep["hbiwkt"] = []
wg["hspol"] = 20
dep["hspol"] = []
wg["ntjawca"] = 63
dep["ntjawca"] = []
wg["yuobv"] = 91
dep["yuobv"] = ["vtdpkof", "basjwp", "pfvpb"]
wg["lqqkjjr"] = 36
dep["lqqkjjr"] = []
wg["zzqwzy"] = 48
dep["zzqwzy"] = ["cnbzj", "vftqnj", "mywezi"]
wg["goyzt"] = 22
dep["goyzt"] = []
wg["apghde"] = 44
dep["apghde"] = []
wg["ahrdgu"] = 23
dep["ahrdgu"] = ["ismgnve", "rwheyic"]
wg["vqiqglo"] = 95
dep["vqiqglo"] = []
wg["ruclz"] = 25
dep["ruclz"] = []
wg["wuqbe"] = 98
dep["wuqbe"] = []
wg["nedbkp"] = 49
dep["nedbkp"] = []
wg["fpmipcr"] = 40
dep["fpmipcr"] = []
wg["gadnfmt"] = 81
dep["gadnfmt"] = []
wg["kxrfley"] = 55
dep["kxrfley"] = []
wg["thlbs"] = 59
dep["thlbs"] = ["iqsvbk", "tbyihc"]
wg["wqvtdc"] = 126
dep["wqvtdc"] = ["uyjre", "dvkrlzc"]
wg["omfvqhv"] = 29
dep["omfvqhv"] = ["iorlbdv", "fwddmmv"]
wg["lihivo"] = 81
dep["lihivo"] = []
wg["ligev"] = 60
dep["ligev"] = []
wg["iabqb"] = 12
dep["iabqb"] = []
wg["zwjqar"] = 71
dep["zwjqar"] = []
wg["ddsqd"] = 61
dep["ddsqd"] = []
wg["wwvad"] = 23
dep["wwvad"] = ["owzybm", "gavjzk", "gxobd"]
wg["plhybj"] = 48
dep["plhybj"] = []
wg["rgyamx"] = 79
dep["rgyamx"] = []
wg["trxgpy"] = 82
dep["trxgpy"] = []
wg["vzxvex"] = 66
dep["vzxvex"] = []
wg["favzt"] = 69
dep["favzt"] = ["qxfan", "pyyuj", "lhahl"]
wg["atrmuc"] = 1081
dep["atrmuc"] = ["qrsgca", "bhthbfj"]
wg["mqrfbqc"] = 9769
dep["mqrfbqc"] = ["vbqtd", "ykuto", "mgktiii", "iylwxgn"]
wg["ihkcni"] = 66
dep["ihkcni"] = []
wg["ttxrd"] = 54
dep["ttxrd"] = []
wg["dvhbwl"] = 64
dep["dvhbwl"] = []
wg["nlhxju"] = 31
dep["nlhxju"] = []
wg["kjwvqdz"] = 140
dep["kjwvqdz"] = ["zocaag", "gszqlv"]
wg["gulset"] = 80
dep["gulset"] = []
wg["vubst"] = 114
dep["vubst"] = ["giupn", "vckqsrm"]
wg["pvejq"] = 52
dep["pvejq"] = []
wg["lhahl"] = 34
dep["lhahl"] = []
wg["rqoczb"] = 310
dep["rqoczb"] = ["ropzx", "xdsbnr"]
wg["xhhhix"] = 259
dep["xhhhix"] = []
wg["ictdnyf"] = 1551
dep["ictdnyf"] = ["ezfky", "ckxblyq"]
wg["jexvtb"] = 15
dep["jexvtb"] = []
wg["fmlhgs"] = 103
dep["fmlhgs"] = ["ntjawca", "jwpwt"]
wg["fcymcb"] = 17
dep["fcymcb"] = ["mwelezd", "jaoiiae"]
wg["cepddei"] = 195
dep["cepddei"] = ["ppymmsf", "mcdmpq", "tozwp"]
wg["suzsw"] = 28
dep["suzsw"] = []
wg["dlnyi"] = 59
dep["dlnyi"] = []
wg["nzrfhb"] = 198
dep["nzrfhb"] = ["xwpwer", "vjwlck"]
wg["kmnjo"] = 35
dep["kmnjo"] = []
wg["itvhd"] = 30
dep["itvhd"] = []
wg["tpbgp"] = 11
dep["tpbgp"] = []
wg["syykbn"] = 127
dep["syykbn"] = ["teastj", "ntazqjk"]
wg["vhilqk"] = 86
dep["vhilqk"] = []
wg["ctpdk"] = 31
dep["ctpdk"] = ["yzciq", "ljlotlp"]
wg["putpp"] = 92
dep["putpp"] = ["pbrdt", "ihkcni", "sxdljm"]
wg["peydhei"] = 737
dep["peydhei"] = ["dojvyuv", "nnogow", "lwygknn", "ndajgou"]
wg["yzciq"] = 99
dep["yzciq"] = []
wg["xmfzu"] = 83
dep["xmfzu"] = []
wg["plzgfx"] = 98
dep["plzgfx"] = []
wg["qckem"] = 28
dep["qckem"] = []
wg["kuakyv"] = 77
dep["kuakyv"] = []
wg["qpixldb"] = 85
dep["qpixldb"] = []
wg["nnjbjm"] = 23
dep["nnjbjm"] = ["cgwnn", "veclzy", "rzqffr"]
wg["nrkdm"] = 200
dep["nrkdm"] = ["dgtvwiy", "qtbhnxr"]
wg["xwkski"] = 59
dep["xwkski"] = []
wg["mgktiii"] = 827
dep["mgktiii"] = ["ggbxd", "gjfoe", "qoapjhr"]
wg["elusirt"] = 106
dep["elusirt"] = ["appok", "avhkram"]
wg["ttkboa"] = 24
dep["ttkboa"] = []
wg["ckxblyq"] = 71
dep["ckxblyq"] = []
wg["disan"] = 18
dep["disan"] = []
wg["owresw"] = 73
dep["owresw"] = []
wg["pyuuxw"] = 39
dep["pyuuxw"] = []
wg["hwsrjah"] = 176
dep["hwsrjah"] = ["pvejq", "cruxrmy", "vjwivnq"]
wg["skbprng"] = 44
dep["skbprng"] = []
wg["lkyeyn"] = 14
dep["lkyeyn"] = []
wg["mdtniv"] = 82
dep["mdtniv"] = ["eexkce", "oiiagw"]
wg["ljhezx"] = 130
dep["ljhezx"] = ["jpxogsl", "pjnyxo"]
wg["upsiumf"] = 18
dep["upsiumf"] = []
wg["glgrdm"] = 14
dep["glgrdm"] = []
wg["rvcmif"] = 288
dep["rvcmif"] = ["jdmjou", "ddmrgzp"]
wg["wvsspk"] = 25
dep["wvsspk"] = ["lqnwffm", "edgplu", "qyzja"]
wg["umljkr"] = 45
dep["umljkr"] = []
wg["ggbxd"] = 67
dep["ggbxd"] = ["jikpfbk", "siqksje"]
wg["kuujprz"] = 67
dep["kuujprz"] = ["ctatrbo", "xibdlh", "wyuwk", "siflauk", "iigqfh", "jhwltnv"]
wg["aklagd"] = 201
dep["aklagd"] = []
wg["lprpgxe"] = 65
dep["lprpgxe"] = []
wg["auvxopo"] = 42
dep["auvxopo"] = []
wg["uorika"] = 69
dep["uorika"] = []
wg["avbgwvm"] = 81
dep["avbgwvm"] = []
wg["nnogow"] = 96
dep["nnogow"] = []
wg["iybvphk"] = 85
dep["iybvphk"] = []
wg["sxapjc"] = 129
dep["sxapjc"] = ["peydhei", "sehxgj", "lgtffok"]
wg["utrdhz"] = 75
dep["utrdhz"] = []
wg["nbvwta"] = 153
dep["nbvwta"] = ["bbviexo", "pzgvdt"]
wg["jzgpty"] = 44
dep["jzgpty"] = []
wg["qqzhz"] = 32
dep["qqzhz"] = ["eyreht", "xxswgx"]
wg["ropzx"] = 8
dep["ropzx"] = []
wg["xaanoft"] = 42
dep["xaanoft"] = ["cwgrjoh", "uorika", "uobwwa"]
wg["ybnpc"] = 307
dep["ybnpc"] = ["dibqua", "ozfsktz", "txrxyqh"]
wg["cfvlt"] = 753
dep["cfvlt"] = ["rusayd", "feiki", "ucsxzhl"]
wg["ruxuw"] = 43
dep["ruxuw"] = []
wg["ywpjusg"] = 64
dep["ywpjusg"] = ["joxmxc", "mzksj"]
wg["qtcqtv"] = 59
dep["qtcqtv"] = []
wg["qwddgc"] = 82
dep["qwddgc"] = []
wg["eyckbl"] = 58
dep["eyckbl"] = []
wg["lgsda"] = 44
dep["lgsda"] = ["lcazsyd", "mwdfwe", "nnsial"]
wg["tlvpv"] = 36
dep["tlvpv"] = []
wg["rlqwaz"] = 901
dep["rlqwaz"] = ["sizfqfs", "ehynj", "wzjbp", "vubst"]
wg["fgbnlu"] = 66
dep["fgbnlu"] = []
wg["zvmhx"] = 105
dep["zvmhx"] = ["tcsoaw", "rtnpvf", "lbkvgme", "xtttnfp"]
wg["oiiagw"] = 44
dep["oiiagw"] = []
wg["jpxogsl"] = 30
dep["jpxogsl"] = []
wg["lomhz"] = 78
dep["lomhz"] = []
wg["calvq"] = 85
dep["calvq"] = ["ccghjn", "lpascsz", "zkecjv"]
wg["ljlotlp"] = 99
dep["ljlotlp"] = []
wg["jqqxv"] = 59
dep["jqqxv"] = []
wg["iqzdu"] = 187
dep["iqzdu"] = ["itygd", "cdvmqs"]
wg["ugkey"] = 86
dep["ugkey"] = []
wg["tjjrys"] = 94
dep["tjjrys"] = []
wg["dtjhnzr"] = 85
dep["dtjhnzr"] = []
wg["tqeeva"] = 214
dep["tqeeva"] = ["xwkski", "rkjmp"]
wg["tznkdt"] = 12
dep["tznkdt"] = []
wg["daiah"] = 26
dep["daiah"] = []
wg["cwgrjoh"] = 69
dep["cwgrjoh"] = []
wg["dibqua"] = 24
dep["dibqua"] = ["rgyamx", "gcichoe"]
wg["scqutwb"] = 94
dep["scqutwb"] = []
wg["yeifw"] = 71
dep["yeifw"] = []
wg["dyhate"] = 18
dep["dyhate"] = []
wg["acgrw"] = 44
dep["acgrw"] = []
wg["fndpz"] = 18
dep["fndpz"] = []
wg["pynomi"] = 170
dep["pynomi"] = ["kgzqclo", "ygvkw"]
wg["kcyiwqs"] = 35
dep["kcyiwqs"] = ["givljl", "yntnjp"]
wg["lbkvgme"] = 223
dep["lbkvgme"] = ["jadome", "dtwbpl", "ktgfsm"]
wg["ygvkw"] = 71
dep["ygvkw"] = []
wg["dgsutv"] = 25
dep["dgsutv"] = []
wg["rlywif"] = 72
dep["rlywif"] = []
wg["nevpm"] = 49
dep["nevpm"] = []
wg["xtttnfp"] = 73
dep["xtttnfp"] = ["heumdl", "axgpyq", "utrdhz", "paeea"]
wg["ptmqo"] = 284
dep["ptmqo"] = []
wg["ibmcytl"] = 11
dep["ibmcytl"] = []
wg["ejwno"] = 80
dep["ejwno"] = []
wg["mcdmpq"] = 19
dep["mcdmpq"] = []
wg["azvke"] = 170
dep["azvke"] = ["wscktm", "jexvtb"]
wg["govhrck"] = 176
dep["govhrck"] = ["vuqriq", "crfse", "eoditdi"]
wg["tzjzmmv"] = 78
dep["tzjzmmv"] = []
wg["dhjrv"] = 48
dep["dhjrv"] = []
wg["dlifqat"] = 49
dep["dlifqat"] = []
wg["ruhqn"] = 94
dep["ruhqn"] = []
wg["mhtzh"] = 86
dep["mhtzh"] = []
wg["bhhgpe"] = 124
dep["bhhgpe"] = ["bywwy", "xguqlvl"]
wg["ucicsdu"] = 199
dep["ucicsdu"] = ["itvizjy", "wsnqied"]
wg["agwyte"] = 498
dep["agwyte"] = ["gcczhgd", "lclbeiq", "rgndu"]
wg["gapjnb"] = 200
dep["gapjnb"] = []
wg["pitmcu"] = 27
dep["pitmcu"] = []
wg["vtdpkof"] = 44
dep["vtdpkof"] = []
wg["joxmxc"] = 68
dep["joxmxc"] = []
wg["mclgebd"] = 89
dep["mclgebd"] = []
wg["refgrip"] = 35
dep["refgrip"] = []
wg["hsxru"] = 30
dep["hsxru"] = ["oeeqrsd", "icdlpb", "veycd", "dlrpnot"]
wg["jikpfbk"] = 53
dep["jikpfbk"] = []
wg["usztpox"] = 160
dep["usztpox"] = ["goyzt", "eagggd"]
wg["aqhcy"] = 57
dep["aqhcy"] = []
wg["umhcrc"] = 174
dep["umhcrc"] = []
wg["qwvvha"] = 45
dep["qwvvha"] = []
wg["crxnz"] = 10
dep["crxnz"] = []
wg["mbmzme"] = 37
dep["mbmzme"] = ["qajpehv", "dlifqat", "bponwxc", "hjzehyw"]
wg["uyjre"] = 22
dep["uyjre"] = []
wg["tsbbzu"] = 22
dep["tsbbzu"] = []
wg["tenzzu"] = 67
dep["tenzzu"] = []
wg["ijvuozb"] = 38
dep["ijvuozb"] = []
wg["oypzs"] = 67
dep["oypzs"] = []
wg["ymxlwf"] = 327
dep["ymxlwf"] = ["nzrfhb", "wbogdd", "fujgzbt", "nqkwmyd", "vgugdtt"]
wg["dvgstr"] = 87
dep["dvgstr"] = ["rqhrb", "xtvawvt", "receu"]
wg["yzuygum"] = 57
dep["yzuygum"] = ["oiysq", "jibdphs"]
wg["vuqriq"] = 238
dep["vuqriq"] = []
wg["lsysd"] = 68
dep["lsysd"] = []
wg["meayff"] = 35
dep["meayff"] = []
wg["guztl"] = 73
dep["guztl"] = ["mrbqk", "aoxtau"]
wg["rtnpvf"] = 177
dep["rtnpvf"] = ["pwsye", "nevpm", "nvxlr", "smtbsys"]
wg["zbqpk"] = 112
dep["zbqpk"] = ["apmpzd", "yueoma"]
wg["bbviexo"] = 37
dep["bbviexo"] = []
wg["gimkyms"] = 21
dep["gimkyms"] = []
wg["fjwmd"] = 692
dep["fjwmd"] = ["luayjsp", "njqzaxg", "ywgvsdb"]
wg["igfhu"] = 31
dep["igfhu"] = []
wg["qkhhg"] = 105
dep["qkhhg"] = ["yknwap", "qqqsv"]
wg["ybewhak"] = 122
dep["ybewhak"] = []
wg["xkizl"] = 18
dep["xkizl"] = []
wg["siqksje"] = 53
dep["siqksje"] = []
wg["vtbzq"] = 178
dep["vtbzq"] = ["tenzzu", "ocpzltp"]
wg["giblwzi"] = 7
dep["giblwzi"] = []
wg["atjtgjx"] = 59
dep["atjtgjx"] = []
wg["bjlwfmo"] = 49
dep["bjlwfmo"] = []
wg["jibdphs"] = 64
dep["jibdphs"] = []
wg["cxlfgl"] = 92
dep["cxlfgl"] = []
wg["wltlu"] = 1495
dep["wltlu"] = ["swumt", "qeosq", "guhyk"]
wg["lkqiqa"] = 57
dep["lkqiqa"] = []
wg["qwlepd"] = 44
dep["qwlepd"] = []
wg["rmvry"] = 145
dep["rmvry"] = ["ejzfwt", "pknjpc", "qfhkgt"]
wg["xmpdevf"] = 185
dep["xmpdevf"] = ["rjmdre", "abcyotz"]
wg["utwzg"] = 10
dep["utwzg"] = []
wg["lpascsz"] = 58
dep["lpascsz"] = []
wg["abcyotz"] = 21
dep["abcyotz"] = []
wg["grqjew"] = 73
dep["grqjew"] = []
wg["vindom"] = 25
dep["vindom"] = []
wg["tzmes"] = 28
dep["tzmes"] = []
wg["ktwby"] = 44
dep["ktwby"] = []
wg["gfsnsdu"] = 38
dep["gfsnsdu"] = []
wg["ywlub"] = 66
dep["ywlub"] = []
wg["iryrfjs"] = 31
dep["iryrfjs"] = []
wg["fwfpmti"] = 34
dep["fwfpmti"] = []
wg["givljl"] = 68
dep["givljl"] = []
wg["edebwk"] = 161
dep["edebwk"] = ["dtjhnzr", "cipxwb", "uqcqc"]
wg["aziwd"] = 48
dep["aziwd"] = []
wg["ajtjnwp"] = 46
dep["ajtjnwp"] = ["clfrs", "qdwkxia"]
wg["nvlqab"] = 27
dep["nvlqab"] = []
wg["dvwsrc"] = 1517
dep["dvwsrc"] = ["jiyuw", "dvtdje"]
wg["basjwp"] = 44
dep["basjwp"] = []
wg["rhchuf"] = 67
dep["rhchuf"] = ["sedysm", "nedbkp"]
wg["cdvmqs"] = 57
dep["cdvmqs"] = []
wg["dkdovw"] = 262
dep["dkdovw"] = ["afglbpz", "ovfduq"]
wg["seeqikh"] = 10944
dep["seeqikh"] = ["mztuzb", "zovbvcr", "nnjbjm"]
wg["bgcrdqu"] = 174
dep["bgcrdqu"] = []
wg["huqpiix"] = 121
dep["huqpiix"] = ["eptcqns", "aiget"]
wg["bywwy"] = 74
dep["bywwy"] = []
wg["aujxmm"] = 89
dep["aujxmm"] = []
wg["xecqd"] = 12
dep["xecqd"] = []
wg["tbppaj"] = 94
dep["tbppaj"] = []
wg["zkecjv"] = 58
dep["zkecjv"] = []
wg["utncpu"] = 84
dep["utncpu"] = []
wg["grrycy"] = 73
dep["grrycy"] = []
wg["htlpx"] = 25
dep["htlpx"] = []
wg["pvtat"] = 13
dep["pvtat"] = []
wg["dfdlzzt"] = 71
dep["dfdlzzt"] = []
wg["uwaij"] = 16
dep["uwaij"] = []
wg["edgplu"] = 94
dep["edgplu"] = []
wg["aflmt"] = 153
dep["aflmt"] = ["puyiail", "jaiqusy"]
wg["eoditdi"] = 10
dep["eoditdi"] = ["boqtohm", "odsrv", "iblrer"]
wg["imshim"] = 39
dep["imshim"] = []
wg["nioeugr"] = 38
dep["nioeugr"] = []
wg["eagggd"] = 22
dep["eagggd"] = []
wg["ulznkvm"] = 211
dep["ulznkvm"] = ["meayff", "oqiye"]
wg["psrzr"] = 213
dep["psrzr"] = ["bwdfws", "sdrhiyo"]
wg["vmmww"] = 69
dep["vmmww"] = []
wg["blofdav"] = 18
dep["blofdav"] = []
wg["zbfyg"] = 49
dep["zbfyg"] = ["xoqxrbl", "dgnpr"]
wg["qzhyumq"] = 25
dep["qzhyumq"] = []
wg["dpcmm"] = 69
dep["dpcmm"] = []
wg["qvmorke"] = 57
dep["qvmorke"] = []
wg["exuwhfs"] = 89
dep["exuwhfs"] = ["qumahjn", "kkvkz"]
wg["rdqvi"] = 56
dep["rdqvi"] = []
wg["axlgwj"] = 38
dep["axlgwj"] = []
wg["vbxqhoy"] = 744
dep["vbxqhoy"] = ["nquonb", "zhudrmb", "ryxkvxj"]
wg["rqlaf"] = 67
dep["rqlaf"] = []
wg["mlrdsj"] = 107
dep["mlrdsj"] = ["tzdtm", "etmvojh"]
wg["tnzqj"] = 1057
dep["tnzqj"] = ["nbpic", "ctgbkrb", "bgcrdqu"]
wg["lghygm"] = 73
dep["lghygm"] = []
wg["wvjjht"] = 60
dep["wvjjht"] = []
wg["wmvht"] = 36
dep["wmvht"] = []
wg["xibdlh"] = 255
dep["xibdlh"] = ["tgjdwlh", "vyffcrm", "ahridq"]
wg["pjersb"] = 86
dep["pjersb"] = []
wg["pdwesa"] = 407
dep["pdwesa"] = ["ximrdyg", "xaebyo", "qqpsrts", "ucicsdu"]
wg["tflulu"] = 3299
dep["tflulu"] = ["ezcmm", "tnzqj", "njkeu", "ctpjjsh"]
wg["rmkhel"] = 55
dep["rmkhel"] = ["olkcm", "yquqk", "iuydxn"]
wg["odsrv"] = 76
dep["odsrv"] = []
wg["kfbsjv"] = 73
dep["kfbsjv"] = ["ylxxmlt", "whqvs", "edmljb", "bpptuqh", "jwjggy", "nrkdm"]
wg["vywqra"] = 18
dep["vywqra"] = []
wg["bnehbkl"] = 14
dep["bnehbkl"] = []
wg["lkwapf"] = 290
dep["lkwapf"] = ["ttkboa", "xvcikqe"]
wg["kawloxz"] = 45
dep["kawloxz"] = ["rttwea", "nmfvmam", "kwkprrw", "gxnoomf"]
wg["drrvse"] = 21
dep["drrvse"] = []
wg["tklfj"] = 465
dep["tklfj"] = ["fcapw", "omfvqhv", "wgwlbz"]
wg["receu"] = 19
dep["receu"] = []
wg["zqdezgy"] = 72
dep["zqdezgy"] = []
wg["ntkeax"] = 91
dep["ntkeax"] = ["sbgwln", "fgbnlu"]
wg["boqtohm"] = 76
dep["boqtohm"] = []
wg["rpcoxd"] = 252
dep["rpcoxd"] = []
wg["hiqqg"] = 82
dep["hiqqg"] = []
wg["cdyhvr"] = 28
dep["cdyhvr"] = []
wg["snkox"] = 67
dep["snkox"] = ["mspkmg", "lxzucvk", "zsqqhe", "sgkksme"]
wg["zpxqtrg"] = 52
dep["zpxqtrg"] = []
wg["olgsb"] = 93
dep["olgsb"] = []
wg["hikocbe"] = 92
dep["hikocbe"] = []
wg["xwpwer"] = 28
dep["xwpwer"] = []
wg["kzfzp"] = 67
dep["kzfzp"] = []
wg["dfyyjta"] = 33822
dep["dfyyjta"] = ["hvhjh", "ujfeg", "iayzdx"]
wg["hvhjh"] = 6551
dep["hvhjh"] = ["uveybq", "iqbrs", "zrnnyet"]
wg["kjpzwp"] = 160
dep["kjpzwp"] = ["fmvyjwj", "lsysd"]
wg["htyyatf"] = 240
dep["htyyatf"] = ["fndpz", "xtoaq", "hhboca", "llsvd"]
wg["uveybq"] = 947
dep["uveybq"] = ["ywpjusg", "gapjnb", "azvke"]
wg["cqbvru"] = 61
dep["cqbvru"] = []
wg["saqjax"] = 45
dep["saqjax"] = []
wg["emlqbo"] = 18
dep["emlqbo"] = []
wg["jvayv"] = 171
dep["jvayv"] = ["daiah", "fyjowg"]
wg["dtnaqds"] = 33
dep["dtnaqds"] = []
wg["rxuwet"] = 92
dep["rxuwet"] = []
wg["xnuoisk"] = 64
dep["xnuoisk"] = []
wg["etmvojh"] = 80
dep["etmvojh"] = []
wg["eqnpvwk"] = 36
dep["eqnpvwk"] = []
wg["puyiail"] = 18
dep["puyiail"] = []
wg["ijrzzr"] = 77
dep["ijrzzr"] = []
wg["jfuxeo"] = 150
dep["jfuxeo"] = ["xgnqi", "dfzfwun"]
wg["pzgvsxu"] = 282
dep["pzgvsxu"] = ["cltqhc", "ruclz", "vindom"]
wg["tqpgc"] = 1018
dep["tqpgc"] = ["bbxbrsh", "uwxbv", "nlhxju", "hazbs"]
wg["nadbbgx"] = 258
dep["nadbbgx"] = ["akoqk", "izwze"]
wg["qdwkxia"] = 72
dep["qdwkxia"] = []
wg["rbqcbvl"] = 88
dep["rbqcbvl"] = []
wg["wutdi"] = 38
dep["wutdi"] = []
wg["mlrjfy"] = 38
dep["mlrjfy"] = []
wg["efxakc"] = 154
dep["efxakc"] = ["dfaro", "lcsqgx"]
wg["dacbtyf"] = 57
dep["dacbtyf"] = []
wg["mevea"] = 303
dep["mevea"] = ["qaxvec", "esiwujq", "plzfjy"]
wg["dsxhhub"] = 12
dep["dsxhhub"] = []
wg["wjzyxt"] = 252
dep["wjzyxt"] = []
wg["pnoxhe"] = 27
dep["pnoxhe"] = ["vjqjwk", "enpprra", "ftmwqqj"]
wg["kkvkz"] = 71
dep["kkvkz"] = []
wg["clfrs"] = 72
dep["clfrs"] = []
wg["zovbvcr"] = 383
dep["zovbvcr"] = ["diyvlug", "xhodnx", "repak", "zjfrc"]
wg["jwjggy"] = 210
dep["jwjggy"] = ["duvrzrl", "zsxbg"]
wg["xjfkrjs"] = 33
dep["xjfkrjs"] = ["ibzalz", "rxuwet"]
wg["gtvnow"] = 180
dep["gtvnow"] = ["euvev", "kvbdsv"]
wg["etfuhz"] = 123
dep["etfuhz"] = ["zoicqbj", "ajvtdl", "wmvht"]
wg["afglbpz"] = 16
dep["afglbpz"] = []
wg["nquonb"] = 50
dep["nquonb"] = ["avbgwvm", "lihivo"]
wg["nbpic"] = 148
dep["nbpic"] = ["iuoxs", "yxvgj"]
wg["eivrwbt"] = 17
dep["eivrwbt"] = ["yeifw", "podcsx", "fhoprd", "beeeaye"]
wg["gszqlv"] = 38
dep["gszqlv"] = []
wg["yhycc"] = 121
dep["yhycc"] = ["vwkbje", "qzhyumq"]
wg["gjzddf"] = 38
dep["gjzddf"] = []
wg["cxpoqyu"] = 72
dep["cxpoqyu"] = []
wg["emdsyso"] = 89
dep["emdsyso"] = []
wg["qqpsrts"] = 85
dep["qqpsrts"] = ["doudbv", "mmzdk"]
wg["gjwuf"] = 124
dep["gjwuf"] = ["bjlwfmo", "evubadn"]
wg["hkhsc"] = 171
dep["hkhsc"] = ["ipwxws", "yrdgv", "ckswvj", "yjlrwzu", "ptmqo", "ojishwt", "drzrtpi"]
wg["mwtojre"] = 207
dep["mwtojre"] = ["hmetm", "utbev", "wltlu", "ictdnyf"]
wg["fqoqkzk"] = 12
dep["fqoqkzk"] = []
wg["nkhzrd"] = 5
dep["nkhzrd"] = []
wg["enpprra"] = 76
dep["enpprra"] = []
wg["gwcig"] = 75
dep["gwcig"] = []
wg["uqcpah"] = 91
dep["uqcpah"] = []
wg["koued"] = 75
dep["koued"] = ["kxrfley", "tjnyo"]
wg["dtxrjg"] = 22
dep["dtxrjg"] = []
wg["pnkag"] = 93
dep["pnkag"] = ["ofoto", "zzqwzy", "zobjfxe", "blutjw", "aisfhs", "gmoliax"]
wg["iucuw"] = 99
dep["iucuw"] = ["gulset", "drrjnr"]
wg["fhsecp"] = 17
dep["fhsecp"] = []
wg["dgrwv"] = 62
dep["dgrwv"] = []
wg["ibzalz"] = 92
dep["ibzalz"] = []
wg["tbyihc"] = 73
dep["tbyihc"] = []
wg["cleanrs"] = 10
dep["cleanrs"] = []
wg["cibfe"] = 27
dep["cibfe"] = []
wg["ycvvjgc"] = 28
dep["ycvvjgc"] = []
wg["dnphyfm"] = 7185
dep["dnphyfm"] = ["mpulnxr", "sxegjbz", "tklfj"]
wg["xnxdmdb"] = 26
dep["xnxdmdb"] = []
wg["jniisu"] = 34
dep["jniisu"] = []
wg["eaqiocy"] = 93
dep["eaqiocy"] = ["dywjt", "kikfs", "fpmipcr"]
wg["bugtxto"] = 26
dep["bugtxto"] = []
wg["pprkvq"] = 26
dep["pprkvq"] = []
wg["myznok"] = 57
dep["myznok"] = []
wg["iblrer"] = 76
dep["iblrer"] = []
wg["bhmzx"] = 64
dep["bhmzx"] = ["tgoeoh", "ojxyv"]
wg["yibxqhs"] = 52
dep["yibxqhs"] = []
wg["xoqxrbl"] = 93
dep["xoqxrbl"] = []
wg["hoeqoas"] = 99
dep["hoeqoas"] = []
wg["oxvfpna"] = 222
dep["oxvfpna"] = []
wg["okbzzwd"] = 73
dep["okbzzwd"] = []
wg["yhecio"] = 65
dep["yhecio"] = []
wg["esgqip"] = 62
dep["esgqip"] = []
wg["zwofu"] = 30
dep["zwofu"] = []
wg["nnyqes"] = 49
dep["nnyqes"] = []
wg["yydyjr"] = 66
dep["yydyjr"] = []
wg["ztzfled"] = 70
dep["ztzfled"] = []
wg["yvqasth"] = 1018
dep["yvqasth"] = ["lfksu", "xszci"]
wg["eqbvn"] = 153
dep["eqbvn"] = ["plhybj", "kozgi"]
wg["hqmum"] = 79
dep["hqmum"] = ["dfdlzzt", "ulndqey", "zwjqar", "jhxxfq"]
wg["gvayfu"] = 64
dep["gvayfu"] = ["cfvbuip", "rbtvx"]
wg["fsagr"] = 141
dep["fsagr"] = ["lugkrb", "npqroe"]
wg["pfvpb"] = 44
dep["pfvpb"] = []
wg["cvdjts"] = 271
dep["cvdjts"] = ["zmces", "ugkey"]
wg["bcjpzpk"] = 174
dep["bcjpzpk"] = []
wg["jxykl"] = 54
dep["jxykl"] = []
wg["mwdfwe"] = 78
dep["mwdfwe"] = []
wg["diyvlug"] = 133
dep["diyvlug"] = ["ddsqd", "txeucf"]
wg["wbeizj"] = 35
dep["wbeizj"] = []
wg["xxswgx"] = 45
dep["xxswgx"] = []
wg["wfdxfxq"] = 676
dep["wfdxfxq"] = ["irrpz", "wvsspk", "dqtthnn"]
wg["lcsqgx"] = 8
dep["lcsqgx"] = []
wg["lmvmb"] = 93
dep["lmvmb"] = []
wg["cyvplfd"] = 14
dep["cyvplfd"] = []
wg["olkcm"] = 131
dep["olkcm"] = ["mkdiuil", "msbsjpj"]
wg["kloumi"] = 39
dep["kloumi"] = []
wg["xzwjii"] = 63
dep["xzwjii"] = []
wg["zmjfa"] = 82
dep["zmjfa"] = []
wg["fakyd"] = 842
dep["fakyd"] = ["sgtfap", "frbmr", "rhchuf"]
wg["jgzvrf"] = 173
dep["jgzvrf"] = ["hspol", "vbpde"]
wg["slfile"] = 66
dep["slfile"] = []
wg["jwpwt"] = 63
dep["jwpwt"] = []
wg["xhodnx"] = 67
dep["xhodnx"] = ["estwket", "tjjrys"]
wg["ihrhkj"] = 11
dep["ihrhkj"] = []
wg["wlkatbq"] = 188
dep["wlkatbq"] = []
wg["cijfsu"] = 68
dep["cijfsu"] = []
wg["ipqjff"] = 62
dep["ipqjff"] = []
wg["ztaff"] = 6
dep["ztaff"] = []
wg["eecoekq"] = 41
dep["eecoekq"] = []
wg["oaxskk"] = 266
dep["oaxskk"] = ["azwmkej", "rciilr"]
wg["sedysm"] = 49
dep["sedysm"] = []
wg["jhwltnv"] = 19
dep["jhwltnv"] = ["akluijb", "zvtxa", "pvpmt", "bkqexxz"]
wg["xhqgsro"] = 6
dep["xhqgsro"] = []
wg["bmdxyf"] = 318
dep["bmdxyf"] = ["zgslahq", "koued", "yzuygum"]
wg["dmyzfr"] = 18
dep["dmyzfr"] = []
wg["rqrfl"] = 65
dep["rqrfl"] = []
wg["clmyzsu"] = 115
dep["clmyzsu"] = ["mlrjfy", "xiawjb", "kroqr"]
wg["rusayd"] = 901
dep["rusayd"] = ["ylkfgx", "lxsurts"]
wg["tzdtm"] = 80
dep["tzdtm"] = []
wg["dpetvw"] = 71
dep["dpetvw"] = []
wg["eccwi"] = 6
dep["eccwi"] = []
wg["wdssrl"] = 75
dep["wdssrl"] = []
wg["uofigyp"] = 9
dep["uofigyp"] = []
wg["aisfhs"] = 183
dep["aisfhs"] = ["lylaoh", "fujwzoc", "kobcmy"]
wg["dcgarog"] = 15
dep["dcgarog"] = []
wg["eosuf"] = 69
dep["eosuf"] = []
wg["qeosq"] = 66
dep["qeosq"] = []
wg["itxaax"] = 77
dep["itxaax"] = []
wg["mmzdk"] = 77
dep["mmzdk"] = []
wg["dvtdje"] = 40
dep["dvtdje"] = []
wg["aumbaa"] = 28
dep["aumbaa"] = []
wg["wdivd"] = 26
dep["wdivd"] = []
wg["eemfgbx"] = 17
dep["eemfgbx"] = []
wg["dlrpnot"] = 62
dep["dlrpnot"] = []
wg["ugxls"] = 62
dep["ugxls"] = []
wg["qqqsv"] = 98
dep["qqqsv"] = []
wg["lfhaqdn"] = 27
dep["lfhaqdn"] = []
wg["qblnh"] = 45
dep["qblnh"] = []
wg["yknwap"] = 98
dep["yknwap"] = []
wg["ipogzy"] = 76
dep["ipogzy"] = []
wg["irhxzg"] = 124
dep["irhxzg"] = ["utwzg", "crxnz"]
wg["dtwbpl"] = 50
dep["dtwbpl"] = []
wg["lqnwffm"] = 94
dep["lqnwffm"] = []
wg["ygnww"] = 13
dep["ygnww"] = []
wg["xrkca"] = 217
dep["xrkca"] = ["xhqgsro", "avymjz"]
wg["qrsgca"] = 35
dep["qrsgca"] = []
wg["ftgvx"] = 14
dep["ftgvx"] = []
wg["fhoaub"] = 35
dep["fhoaub"] = []
wg["nuuqqqy"] = 94
dep["nuuqqqy"] = []
wg["ppmvpn"] = 94
dep["ppmvpn"] = []
wg["kisjb"] = 57
dep["kisjb"] = []
wg["owzybm"] = 91
dep["owzybm"] = []
wg["jwddn"] = 134
dep["jwddn"] = ["vfosh", "nvdon", "kopmae", "inhqoxd", "xlyvge"]
wg["cnbzj"] = 141
dep["cnbzj"] = ["kuakyv", "vnsrv", "ijrzzr", "dbrnqc"]
wg["wlleabp"] = 179
dep["wlleabp"] = []
wg["lhdhko"] = 66
dep["lhdhko"] = []
wg["bbsuv"] = 439
dep["bbsuv"] = ["ionnpk", "etfuhz", "mobbhp", "exuwhfs"]
wg["umvvwsq"] = 10
dep["umvvwsq"] = []
wg["eibtll"] = 94
dep["eibtll"] = []
wg["otuwt"] = 35
dep["otuwt"] = ["ejwno", "zogylog", "ooiyeep"]
wg["epqsj"] = 137
dep["epqsj"] = ["bugtxto", "hsnbry"]
wg["yuepckc"] = 66
dep["yuepckc"] = ["tqpgc", "pstaxvr", "owtxsq"]
wg["dhzuvup"] = 76
dep["dhzuvup"] = []
wg["crfse"] = 238
dep["crfse"] = []
wg["ibcbvy"] = 6
dep["ibcbvy"] = []
wg["cefbp"] = 78
dep["cefbp"] = []
wg["uhxjy"] = 63
dep["uhxjy"] = []
wg["bponwxc"] = 49
dep["bponwxc"] = []
wg["mcxki"] = 29
dep["mcxki"] = ["rvcmif", "gnozwfo", "mevea", "vtvku", "dmtzxui"]
wg["emqoxss"] = 66
dep["emqoxss"] = ["tnyjkok", "gmpqmio"]
wg["ionnpk"] = 97
dep["ionnpk"] = ["rqlaf", "ktrkhe"]
wg["gasnep"] = 91
dep["gasnep"] = ["qgwcfll", "nkcet"]
wg["avymjz"] = 6
dep["avymjz"] = []
wg["fetns"] = 37
dep["fetns"] = ["zfmeblt", "jtsyj", "rdqvi"]
wg["altsh"] = 89
dep["altsh"] = ["zdvai", "iybvphk"]
wg["kgjcj"] = 242
dep["kgjcj"] = []
wg["bltmlm"] = 93
dep["bltmlm"] = ["xdlvys", "tflulu", "xqrmgdk", "dnphyfm", "kwbni", "uplbokf", "vbsfwqh"]
wg["hikik"] = 15
dep["hikik"] = []
wg["nnofr"] = 71
dep["nnofr"] = ["xxrsnzv", "pucsbv", "rtzce", "kloumi"]
wg["siflauk"] = 271
dep["siflauk"] = ["qckem", "tzmes"]
wg["nkcet"] = 95
dep["nkcet"] = []
wg["ijjfn"] = 34
dep["ijjfn"] = []
wg["itvizjy"] = 20
dep["itvizjy"] = []
wg["numadl"] = 98
dep["numadl"] = []
wg["jkjsi"] = 98
dep["jkjsi"] = []
wg["xaebyo"] = 41
dep["xaebyo"] = ["svadhfo", "hoeqoas"]
wg["yntnjp"] = 68
dep["yntnjp"] = []
wg["axgpyq"] = 75
dep["axgpyq"] = []
wg["civozek"] = 98
dep["civozek"] = []
wg["djizg"] = 33
dep["djizg"] = []
wg["qrtdtt"] = 96
dep["qrtdtt"] = []
wg["kopmae"] = 13
dep["kopmae"] = ["pemna", "vuzsg", "numadl", "wuqbe"]
wg["yztqpc"] = 572
dep["yztqpc"] = ["xxsivgz", "scbycx", "jwezuh"]
wg["msbsjpj"] = 96
dep["msbsjpj"] = []
wg["yjlrwzu"] = 77
dep["yjlrwzu"] = ["mbydswv", "tfzum", "kwhwph"]
wg["tcpqh"] = 15
dep["tcpqh"] = []
wg["fkqkfdu"] = 25
dep["fkqkfdu"] = []
wg["vbqtd"] = 86
dep["vbqtd"] = ["cepddei", "rcxtjte", "zkibug", "wjzyxt", "zhgzg"]
wg["wmcusr"] = 14
dep["wmcusr"] = []
wg["zrnnyet"] = 731
dep["zrnnyet"] = ["zbqpk", "tayyz", "usztpox", "mewfm"]
wg["yadtxl"] = 73
dep["yadtxl"] = []
wg["eqctwan"] = 511
dep["eqctwan"] = ["zitfb", "xjfkrjs", "xddom"]
wg["evmuxia"] = 32
dep["evmuxia"] = []
wg["lbhxdbr"] = 36
dep["lbhxdbr"] = []
wg["fjvoff"] = 62
dep["fjvoff"] = []
wg["wsnqied"] = 20
dep["wsnqied"] = []
wg["vftqnj"] = 57
dep["vftqnj"] = ["dvopaww", "hbvvse", "plzgfx", "jkjsi"]
wg["pwwqvhw"] = 34
dep["pwwqvhw"] = ["fgnsyw", "pyuuxw", "nsbvvsi", "imshim"]
wg["hnjbsg"] = 32
dep["hnjbsg"] = []
wg["pglpu"] = 224
dep["pglpu"] = ["oxvfpna", "umqrwk", "bhmzx"]
wg["etcces"] = 4977
dep["etcces"] = ["eqctwan", "jncex", "zofljd"]
wg["fmvyjwj"] = 68
dep["fmvyjwj"] = []
wg["lgtffok"] = 509
dep["lgtffok"] = ["ruild", "bxpfop", "huqpiix", "tgksxw"]
wg["iqmqju"] = 3619
dep["iqmqju"] = ["oxnfnsv", "bngres", "zkhll"]
wg["xvcikqe"] = 24
dep["xvcikqe"] = []
wg["wvpwez"] = 89
dep["wvpwez"] = []
wg["saijc"] = 96
dep["saijc"] = []
wg["aiget"] = 16
dep["aiget"] = []
wg["fdjhpq"] = 66
dep["fdjhpq"] = []
wg["adcbil"] = 47
dep["adcbil"] = []
wg["lrnjjfq"] = 17
dep["lrnjjfq"] = []
wg["teastj"] = 53
dep["teastj"] = []
wg["csybv"] = 33546
dep["csybv"] = ["kdtpg", "wseyo", "etcces", "pnkag"]
wg["zkibug"] = 238
dep["zkibug"] = ["xkfps", "giblwzi"]
wg["pzahn"] = 73
dep["pzahn"] = []
wg["auzded"] = 499
dep["auzded"] = ["tqeeva", "fyrqw", "oaxskk", "hwsrjah", "jfqanu"]
wg["bhthbfj"] = 35
dep["bhthbfj"] = []
wg["dvkrlzc"] = 22
dep["dvkrlzc"] = []
wg["dgrfhvi"] = 67
dep["dgrfhvi"] = []
wg["qcghv"] = 67
dep["qcghv"] = ["ezkqh", "uqcpah"]
wg["sdrhiyo"] = 27
dep["sdrhiyo"] = []
wg["kwhwph"] = 69
dep["kwhwph"] = []
wg["ejzfwt"] = 52
dep["ejzfwt"] = []
wg["vuzsg"] = 98
dep["vuzsg"] = []
wg["tgoeoh"] = 79
dep["tgoeoh"] = []
wg["vrpqev"] = 64
dep["vrpqev"] = ["axlgwj", "gfsnsdu", "kpdbki", "mvqfvit"]
wg["vrydu"] = 43
dep["vrydu"] = []
wg["vnsrv"] = 77
dep["vnsrv"] = []
wg["gjfoe"] = 161
dep["gjfoe"] = ["mcduoz", "eccwi"]
wg["ppgaoz"] = 65
dep["ppgaoz"] = ["pejmc", "cbwbdsv", "otuwt"]
wg["xddom"] = 39
dep["xddom"] = ["aujxmm", "fjrpc"]
wg["lxsurts"] = 6
dep["lxsurts"] = []
wg["tayyz"] = 50
dep["tayyz"] = ["vtzdfjg", "ijvux"]
wg["kwzrzn"] = 71
dep["kwzrzn"] = []
wg["doudbv"] = 77
dep["doudbv"] = []
wg["ahridq"] = 24
dep["ahridq"] = []
wg["dqtthnn"] = 217
dep["dqtthnn"] = ["hgsng", "jwzmsv"]
wg["haeymgy"] = 85
dep["haeymgy"] = []
wg["zoicqbj"] = 36
dep["zoicqbj"] = []
wg["bcjxhps"] = 58
dep["bcjxhps"] = []
wg["swumt"] = 66
dep["swumt"] = []
wg["iywwyn"] = 43
dep["iywwyn"] = []
wg["pirieql"] = 92
dep["pirieql"] = []
wg["ntazqjk"] = 53
dep["ntazqjk"] = []
wg["ajwxaa"] = 208
dep["ajwxaa"] = ["wtvffu", "gmdcbyg", "intuzzk"]
wg["wscktm"] = 15
dep["wscktm"] = []
wg["itygd"] = 57
dep["itygd"] = []
wg["hjzehyw"] = 49
dep["hjzehyw"] = []
wg["jdmjou"] = 69
dep["jdmjou"] = []
wg["iavuhwe"] = 49
dep["iavuhwe"] = []
wg["tpfuxx"] = 26
dep["tpfuxx"] = []
wg["wseyo"] = 5904
dep["wseyo"] = ["beraoor", "zbhwrc", "ybnpc"]
wg["rlapq"] = 322
dep["rlapq"] = ["adcbil", "rbfbf"]
wg["jtsyj"] = 56
dep["jtsyj"] = []
wg["zouml"] = 199
dep["zouml"] = ["dmyzfr", "udjcwm"]
wg["txrxyqh"] = 107
dep["txrxyqh"] = ["rdufpid", "yhunajf", "dgsutv"]
wg["zobjfxe"] = 525
dep["zobjfxe"] = ["ylbpwah", "nadbbgx", "putpp"]
wg["inhqoxd"] = 327
dep["inhqoxd"] = ["cdafdq", "zucsr", "pprkvq"]
wg["ndajgou"] = 96
dep["ndajgou"] = []
wg["paeea"] = 75
dep["paeea"] = []
wg["yrdgv"] = 284
dep["yrdgv"] = []
wg["sbcuc"] = 65
dep["sbcuc"] = []
wg["aklrjg"] = 10
dep["aklrjg"] = []
wg["kbjnzw"] = 117
dep["kbjnzw"] = ["xtzqooh", "lfhaqdn"]
wg["cfafhwl"] = 34
dep["cfafhwl"] = []
wg["htyeqf"] = 94
dep["htyeqf"] = []
wg["dmiqf"] = 62
dep["dmiqf"] = []
wg["tghoyv"] = 210
dep["tghoyv"] = ["iywwyn", "gypsfc"]
wg["plxdglq"] = 24
dep["plxdglq"] = []
wg["qxwlhxh"] = 41
dep["qxwlhxh"] = []
wg["pknjpc"] = 52
dep["pknjpc"] = []
wg["njqzaxg"] = 23
dep["njqzaxg"] = ["saijc", "jmbiky"]
wg["tckcxhb"] = 68
dep["tckcxhb"] = ["yfzjc", "nwjibjk", "igfhu", "iryrfjs"]
wg["xdlvys"] = 3528
dep["xdlvys"] = ["zcjrk", "wkrtcw", "kuujprz"]
wg["dcngdo"] = 47
dep["dcngdo"] = []
wg["pazbvum"] = 57
dep["pazbvum"] = []
wg["kvags"] = 67
dep["kvags"] = []
wg["nuuwbui"] = 35
dep["nuuwbui"] = []
wg["whcxfwf"] = 115
dep["whcxfwf"] = ["vrydu", "ruxuw"]
wg["ojishwt"] = 126
dep["ojishwt"] = ["llcbiqi", "namzy"]
wg["uwxbv"] = 31
dep["uwxbv"] = []
wg["vrqeade"] = 102
dep["vrqeade"] = ["emlqbo", "vywqra", "upsiumf", "blofdav"]
wg["rixge"] = 338
dep["rixge"] = []
wg["dmtzxui"] = 98
dep["dmtzxui"] = ["auhio", "qwddgc", "hiqqg", "iezdimc"]
wg["texfyi"] = 144
dep["texfyi"] = []
wg["cgwnn"] = 384
dep["cgwnn"] = ["nioeugr", "gjzddf"]
wg["mwzaxaj"] = 59
dep["mwzaxaj"] = ["csybv", "febjzqn", "bltmlm", "dfyyjta", "ljaktj", "vmyda", "vbcfe"]
wg["yquqk"] = 83
dep["yquqk"] = ["wvjjht", "edyqn", "frleu", "puxaz"]
wg["jaoiiae"] = 81
dep["jaoiiae"] = []
wg["pucsbv"] = 39
dep["pucsbv"] = []

pgm = []
for k in dep.keys():
    pgm.append(k)
for k in dep.keys():
    for s in dep[k]:
        pgm.remove(s)
print(pgm)


def weight(name):
    res = []
    for son in dep[name]:
        res.append({"n":son, "cw":weight(son)})
    for i in range(len(res)-1):
        for j in range(i+1,len(res)):
            if res[i]["cw"]!=res[j]["cw"]:
                print(res[i],res[j])
    sm=0
    for i in res:
        sm+=i["cw"]
    return wg[name]+sm

print(pgm[0],weight(pgm[0]))




